### ISSUE TITLE
Add CloudNative-PG CRD's

### ISSUE THREAD

**Issue by Ornias1993** [datreeio/CRDs-catalog#117]
CloudNative-PG, is a project building a postgresql operator.
Worthwhile to have the CRD's added for this one.

**Comment by eyarz** [comment]
the code for the schema can be found here:
https://github.com/cloudnative-pg/cloudnative-pg/tree/main/config/crd/bases

**Comment by Ornias1993** [comment]
> the code for the schema can be found here: https://github.com/cloudnative-pg/cloudnative-pg/tree/main/config/crd/bases

For the CRD yes, not the schema though...
Tried schema extractor, didn't work nicely with my k3s distro and I, sadfully, have other opensource work that takes priority :(

**Comment by eyarz** [comment]
you can run [this script](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) on the [CRD itself](https://github.com/cloudnative-pg/cloudnative-pg/tree/main/config/crd/bases), and it will generate the CR json schema.

**Comment by Ornias1993** [comment]
Sorry, I currently are otherwise pre-occupied.
The readme stated that I should then just file an issue instead.

**Comment by eyarz** [comment]
@Ornias1993 you're right.
I'm just adding the comments if someone from the community will want to pitch in and help with that.

**Comment by Ornias1993** [comment]
> @Ornias1993 you're right.
> I'm just adding the comments if someone from the community will want to pitch in and help with that.

Cool thank! :)

**Comment by maxnrb** [comment]
Hi @Ornias1993, I've just created a PR to add CloudnativePG CRDs : https://github.com/datreeio/CRDs-catalog/pull/183, so coming soon
