### ISSUE TITLE
Update schema of Traefik

### ISSUE THREAD

**Issue by ad-m-ss** [datreeio/CRDs-catalog#119]
Hi,

There are schema for Traefik: https://github.com/datreeio/CRDs-catalog/tree/main/traefik.containo.us

However, it fails to be detected by kubeconform, because they published it as `v1` now:

```
$ helm kubeconform ../. --values ./preview.yaml
ERROR: Testing failed: kubeconform failed: failed to run kubeconform: rc=1
stdin - IngressRoute release-name-traefik-sso-chart-auth-tls failed validation: could not find schema for IngressRoute
stdin - IngressRoute release-name-traefik-dashboard failed validation: could not find schema for IngressRoute
stdin - Middleware release-name-traefik-sso-chart-traefik-forward-auth failed validation: could not find schema for Middleware
stdin - ServersTransport release-name-traefik-sso-chart-insecure failed validation: could not find schema for ServersTransport
Error: plugin "kubeconform" exited with error
$ cat ../.kubeconform
schema-location:
  - default
  - https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
```

See https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-crd/ for their documentation.

I'm open to help work on this but I miss some tips about the best way to do it (see #118).

**Comment by eyarz** [comment]
you are correct, we don't have v1 in the catalog for traefik so it will not work.
feel free to open a PR and add the missing v1 schemas :)

There are two ways to extract the schemas:
1) you can run [this script](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) with the [CRD itself](https://github.com/traefik/traefik/blob/master/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml), and it will generate the CR json schema.
2) you can install traefik v1 on your cluster and extract the schemas with the [CRD Extractor](https://github.com/datreeio/CRDs-catalog#crd-extractor)

both options are doing the same process, but I see you're familiar with python, so I think option 1 will be easier for you.

**Comment by jacksgt** [comment]
@eyarz I believe this can be closed since https://github.com/datreeio/CRDs-catalog/pull/166 was merged.
