### ISSUE TITLE
failing to fetch CRDs still prints success message

### ISSUE THREAD

**Issue by eyarz** [datreeio/CRDs-catalog#12]
**steps:**
Download the [latest release](https://github.com/datreeio/CRDs-catalog/releases/latest/download/crd-extractor.zip) from this repository.
Extract, and run the utility: `./crd-extractor`

**expected:**
if the utility encounters an error while parsing CRDs it should not print a success message

**actual:**
![image](https://user-images.githubusercontent.com/19731161/172167977-49b9b9c2-9ee6-40c1-b14e-4eb8cb826430.png)

**Comment by hadar-co** [comment]
Fixed.
