### ISSUE TITLE
CRD Extractor utility inspects API group and organizes schemas by subdirectory

### ISSUE THREAD

**Issue by bmuschko** [datreeio/CRDs-catalog#147]
I think it would be helpful if the tool could have a look at the value of the `spec.group` attribute, create a subdirectory for it under `$HOME/.datree/crdSchemas`, and organize the corresponding schemas underneath it. This will help with avoiding to manually organize the schemas before providing the pull request for this repository.

**Comment by hadar-co** [comment]
@bmuschko good idea, we will prioritize and implement it 👍

**Comment by bmuschko** [comment]
Perfect, thanks!
