### ISSUE TITLE
Missing of 'ingressClassName' in cert-manager.io/issuer_v1

### ISSUE THREAD

**Issue by adasescu** [datreeio/CRDs-catalog#208]
Hi,

In our project we're using `ingressClassName` field to specify Ingress class in cert-manager Issuer. When schema validation runs is failing with error: `additionalProperties 'ingressClassName' not allowed`
I've noticed that this field was removed from the catalog in this [PR](https://github.com/datreeio/CRDs-catalog/pull/180). Is there any particular reason for this? 
In the official cert-manager [repo](https://github.com/cert-manager/cert-manager/blob/v1.12.0/deploy/crds/crd-issuers.yaml#L488C35-L488C35) `ingressClassName` field is present.

Regards,
Ada

**Comment by eyarz** [comment]
no particular reason, probably just a mistake 😅
you can open a PR with the latest schema updated and I will merge it.
