### ISSUE TITLE
Sooo... what's happening to this repo?

### ISSUE THREAD

**Issue by yannh** [datreeio/CRDs-catalog#214]
Hey datree :wave:  I heard you unfortunately had to close shop, and I'm really sorry for everyone who lost their job as a consequence :disappointed: Hope everyone finds a new place really soon. 

On your main repo you mention that "All the archived open source repositories under datreeio org will no longer be maintained and accept any new code changes, including any security patches." -  this repo has not been archived though, and here have been a few PRs merged since :thinking:   is there a community effort to keep it up-to-date or at least alive? 

Many thanks for all the work and collaboration through the years :wave:

**Comment by eyarz** [comment]
This repo will be kept alive and maintained.
maybe in the near future, I will move it to my workspace (@eyarz), instead of 'datreeio'.
I'm still reviewing and merging PRs, just got lagging behind a little due to other prioritization :)
