### ISSUE TITLE
Invalid monitoring.coreos.com/alertmanagerconfig_v1alpha1.json

### ISSUE THREAD

**Issue by lsimunec** [datreeio/CRDs-catalog#245]
**Issue**
kubeconform throws this error
`Check JSON formatting: jsonschema: '/spec' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json#/properties/spec/additionalProperties: additionalProperties 'route', 'receivers' not allowed`

**Description**
[AlertmanagerConfig](https://github.com/dcardellino24/CRDs-catalog/blob/817c309b392587210003f736ee36dab4afcc5967/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json) does not reflect prometheus-operator-crd [monitoring.coreos.com_alertmanagerconfigs.yaml](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml).

Possibly introduced today with [PR](https://github.com/datreeio/CRDs-catalog/pull/235) where schema `monitoring.coreos.com/thanosruler_v1.json` has been mistakenly placed inside the AlertmanagerConfig schema `example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml`.

**Comment by lsimunec** [comment]
@dcardellino24 @eyarz

**Comment by eyarz** [comment]
good catch
open a PR and I will merge it

**Comment by lsimunec** [comment]
https://github.com/datreeio/CRDs-catalog/pull/246

**Comment by kellsbells** [comment]
Is there a reason why this hasn't been merged yet? We've been waiting on it.

**Comment by lsimunec** [comment]
@eyarz please review https://github.com/datreeio/CRDs-catalog/pull/246

**Comment by marcelloale** [comment]
please review #246
