### ISSUE TITLE
Is this still maintained? YES!

### ISSUE THREAD

**Issue by userbradley** [datreeio/CRDs-catalog#310]
Howdy,

is this at all still maintained?

There's close to 40 PR's open that have had no attention, and 16 Issues that have had no input from maintainers.

Is this project maintained? Or are you looking for new maintainers? 

## Edit as of May the 24th

There are 2 competing new forks of this

* https://github.com/InfinityFlowApp/CRDs-catalog
* https://github.com/elmy-team/CRDs-catalog

So if you're looking for a CRD schema repo, pick one of those that works for you!

As always, they're probably looking for maintainers, so reach out to them!

## Edit as of the 7th of June

I have become a maintainer on this repo! Woo!

**Comment by pauloconnor** [comment]
It looks like Datree shut down some time ago, so I imagine this GitHub org is abandoned https://www.linkedin.com/posts/eyar-zilberman_hi-shimon-and-eyar-the-founders-of-datree-activity-7090315925777715200-E32N?utm_source=share&utm_medium=member_desktop

**Comment by ElanHasson** [comment]
aww sad. I have one here-- https://github.com/InfinityFlowApp/CRDs-catalog

**Comment by pauloconnor** [comment]
It might be worth chatting to the kubeconform folks, and seeing if they're willing to repoint to your fork https://github.com/yannh/kubeconform?tab=readme-ov-file#customresourcedefinition-crd-support They may be interested in hosting their own.

**Comment by ElanHasson** [comment]
I'm open to whatever works @pauloconnor -- We couldn't wait any longer for green builds for us, so we took destiny into our own hands a few months ago.

**Comment by ElanHasson** [comment]
👋🏼 @yannh What are your thoughts on this matter?

**Comment by yannh** [comment]
Hello 👋  I don't really have the bandwidth to maintain this, but i could link to the most active(s) fork(s) in kubeconform's readme?

**Comment by userbradley** [comment]
I was thinking perhaps we can use the org I've created to house this repo and associated ones?

https://github.com/k8s-crds

I'd be looking to put something like this on the repo so the community can control and vote on who has access to manage the repo etc: https://github.com/repository-settings/app

Thoughts?

I also reached out to the UK Governments digital office to see if they would want to support it, but they said no.

My thinking behind putting it on the org I've set up is I've got the time to maintain it, I've got no agenda here other than similar stories to this

> We couldn't wait any longer for green builds for us

Thoughts? Disagreements?

**Comment by ElanHasson** [comment]
@userbradley i'm not opposed to anything here-- just trying to control my destiny :)

**Comment by jacksgt** [comment]
I think creating a Github organization is a good idea, so we can stop handing around the maintainership of this project like a hot potato. 
Ideally alongside a couple of maintainers (not just a single person) who can review PRs etc.

**Comment by eyarz** [comment]
Hi all
Apparently, all my emails from GitHub went to the wrong email address (I fixed that). In the next few days, I will review all PRs and approve them. I will continue to maintain this project, regardless of the fact that we closed Datree. 

If someone wants to help maintain this project, I would be more than happy to get some help :)

**Comment by userbradley** [comment]
@eyarz please put me down as a maintainer, more than happy to take this repo over!

**Comment by pauloconnor** [comment]
+1 to moving this to it's own org, but we definitely need some more folks added to the repo short term. I'm not sure what the best approach for picking folks is, but I'm happy to help in whatever way I can to get this repo back on track.

**Comment by eyarz** [comment]
Thank you all for the support! (@pauloconnor DM you on LinkedIn)
let's start by adding some new maintainers to this project and getting it back on track. 
after that, we can discuss whether it makes sense to move this project to a new organization.

**Comment by ElanHasson** [comment]
Agree on org, would like to be a maintainer as well.

How can we make the entire process easier?

I was thinking that we can build an index of CRD definition locations and automatically update the repository when the crd changes.

**Comment by eyarz** [comment]
> Agree on org, would like to be a maintainer as well.
> 
> How can we make the entire process easier?
> 
> I was thinking that we can build an index of CRD definition locations and automatically update the repository when the crd changes.
> 
> [InfinityFlowApp#14](https://github.com/InfinityFlowApp/CRDs-catalog/issues/14)

go for it!
this was my initial idea, and this is why I created the [index file](https://github.com/datreeio/CRDs-catalog/blob/main/index.yaml) from the beginning (but it's not updated anymore)

regarding getting help as a maintainer, I also DM'd you on LinkedIn :)

**Comment by CodeReaper** [comment]
> Agree on org, would like to be a maintainer as well.
> 
> How can we make the entire process easier?
> 
> I was thinking that we can build an index of CRD definition locations and automatically update the repository when the crd changes.
> 
> [InfinityFlowApp#14](https://github.com/InfinityFlowApp/CRDs-catalog/issues/14)

We noticed the slow-down of merges for the catalog too and scheduled a sprint task for rethinking and replacing the catalog, but forgot to tell anyone. Just a small oversight :)

> go for it! this was my initial idea, and this is why I created the [index file](https://github.com/datreeio/CRDs-catalog/blob/main/index.yaml) from the beginning (but it's not updated anymore)
> 
> regarding getting help as a maintainer, I also DM'd you on LinkedIn :)

It seems like re-invented your old idea. :P

We still need to update the sources files to have all the same files as this catalog does, but we have not tracked down all their sources yet. I am hoping for a little community to do that.

Our catalog should be ready once the sources are updated. Take a look:

https://github.com/CodeReaper/CRD-catalog

We are hoping to move the repo to somewhere appropriate and create GitHub groups like core-maintainers and source-maintainers so we can add a CODEOWNER file to allow a large group of people to merge pull requests for `helm-charts.yaml` and `manifest-uris.yaml` and smaller group to maintain the actual code.

We are a bit late to the party, but can we go forward with our repo?

**Comment by eyarz** [comment]
@CodeReaper super cool what you did there!

I agree with the CODEOWNER approach, and I've started onboarding new maintainers from this thread. 
Feel free to open a PR to update the README file to mention your project as well.

**Comment by pauloconnor** [comment]
To close the loop here, I along with two others have been added to the Org, so we'll be helping move this project along in future.

**Comment by eyarz** [comment]
We now have 3 new maintainers added to this project: @ElanHasson @pauloconnor @userbradley
thank you all for the help!! ❤️
