### ISSUE TITLE
GKE issues

### ISSUE THREAD

**Issue by vfarcic** [datreeio/CRDs-catalog#36]
`crd-extractor.sh` fails on GKE.

```bash
 datree-demo git:(main) ./crd-extractor.sh
```

The output:

```
./crd-extractor.sh: line 41: /Users/vfarcic/.datree/crds/To learn more, consult https://cloud.yaml: No such file or directory
Traceback (most recent call last):
  File "/Users/vfarcic/.datree/crds/openapi2jsonschema.py", line 134, in <module>
    for y in yaml.load_all(f, Loader=yaml.SafeLoader):
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/__init__.py", line 93, in load_all
    yield loader.get_data()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 27, in get_node
    return self.compose_document()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/opt/homebrew/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/Users/vfarcic/.datree/crds/NAME                                                       CREATED AT.yaml", line 2, column 50
cp: /Users/vfarcic/.datree/crdSchemas/*.json: No such file or directory
Successfully converted 44 CRDs to JSON schema

To validate a CR using various tools, run the relevant command:

- datree:
$ datree test --schema-location '/Users/vfarcic/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' /path/to/file


- kubeconform:
$ kubeconform -summary -output json -schema-location default -schema-location '/Users/vfarcic/.datree/crdSchemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' /path/to/file

- kubeval:
$ kubeval --additional-schema-locations file:"/Users/vfarcic/.datree/crdSchemas" /path/to/file
```

The same works on Rancher Desktop. Did not yet test it on other Kubernetes distributions.

**Comment by vfarcic** [comment]
It works in Civo as well so I'm guessing the issue is GKE-specific.

**Comment by eyarz** [comment]
It looks like it's failing when trying to access the cluster to download all the CRDs manifests.
do you see any error if you're running the following command:
`kubectl get crds -o yaml`?

**Comment by vfarcic** [comment]
If have full admin rights in that cluster. Retrieving CRDs with `kubectl` works.

**Comment by hadar-co** [comment]
@vfarcic Hi Viktor:)
From the first line of your output, it seems like the CRD name is not parsed correctly.
Can you please run `kubectl get crds` and paste the output here?
Also, it would help to know which CRD failed so we can try to reproduce.
Thanks!

**Comment by vfarcic** [comment]
Reproduced it on a fresh cluster to discard that there is something "special" in the one I used before.

Here's the list of CRDs.

```bash
kubectl get crds
```

```
W0816 19:42:16.377707   95988 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME                                             CREATED AT
backendconfigs.cloud.google.com                  2022-08-16T16:54:33Z
capacityrequests.internal.autoscaling.gke.io     2022-08-16T16:54:15Z
frontendconfigs.networking.gke.io                2022-08-16T16:54:34Z
managedcertificates.networking.gke.io            2022-08-16T16:54:31Z
memberships.hub.gke.io                           2022-08-16T16:57:56Z
serviceattachments.networking.gke.io             2022-08-16T16:54:35Z
servicenetworkendpointgroups.networking.gke.io   2022-08-16T16:54:35Z
updateinfos.nodemanagement.gke.io                2022-08-16T16:54:44Z
volumesnapshotclasses.snapshot.storage.k8s.io    2022-08-16T16:54:43Z
volumesnapshotcontents.snapshot.storage.k8s.io   2022-08-16T16:54:43Z
volumesnapshots.snapshot.storage.k8s.io          2022-08-16T16:54:44Z
```

The script might not be able to handle warnings from `gcloud` (the top of the output). `gcloud` (used by `kubectl`) is sending warnings to stderr.

**Comment by hadar-co** [comment]
Yes this is definitely the issue, the script parses the output and assumes no warnings/errors.

A quick google search turned up a possible solution:
https://stackoverflow.com/a/72302509/9757520

We can try some hacky bash stuff to ignore such warnings, but solving them seems like the right way to go.

What do you think?:)

**Comment by vfarcic** [comment]
That would fix that particular issue. Nevertheless, `gcloud` tends to output warnings quite often so it would be a very short-term fix. Also, there are other warnings unrelated to `gcloud`. For example, if there are many CRDs in a cluster, `kubctl` will output a warning about the delayed response. That would likely result in the same issue. You might want to query Kube API directly instead of going through `kubectl` and parsing the output or, if that's not an option, figure out whether something is a warning or an actual error and, if it's the former, ignore it. The exit code might help (did not check out what it gives in this case), removing the lines with `WARNING`, or something similar. Ultimately, parsing output is unreliable, hence we have APIs :)

**Comment by hadar-co** [comment]
@vfarcic 
We found a way to ignore the text that comes before the actual table of CRDs, so looks like this solves the problem:)
A [new release](https://github.com/datreeio/CRDs-catalog/releases/latest/download/crd-extractor.zip) is available which contains the fix. Let us know that it works for you 👍🏼

**Comment by eyarz** [comment]
This is just a workaround for now. In the future we will convert this utility to use the API instead.
