### ISSUE TITLE
Request to add azureMonitor type for Log forwarder schema

### ISSUE THREAD

**Issue by priyas16** [datreeio/CRDs-catalog#399]
Hi Team,

We were trying to forward our cluster logs into Azure by using the below configuration which is working as expected. 

`apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
  - name: azure-monitor-audit
    type: azureMonitor
    azureMonitor:
      customerId: <WORKSPACE_ID>
      logType: aro_audit_logs
    secret:
      name: azure-monitor-shared-key`

However when we add it in GitHub, it fails with the below validation check, since the output type for azureMonitor is not part of the schema. 

Error:
ClusterLogForwarder instance is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/outputs/0/type' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/logging.openshift.io/clusterlogforwarder_v1.json#/properties/spec/properties/outputs/items/properties/type/enum: value must be one of "syslog", "fluentdForward", "elasticsearch", "kafka", "cloudwatch", "loki", "googleCloudLogging", "splunk", "http"

Request you to please add it in output type, so that we can get our validation completed.

Thanks!

**Comment by eyarz** [comment]
my guess is that the schema is out-of-date
you can open a PR with the updated schema and I will merge it :)

**Comment by priyas16** [comment]
Hi eyarz,

Sure, raised the below PR, could you please review and approve. Thanks!

https://github.com/datreeio/CRDs-catalog/pull/401

**Comment by priyas16** [comment]
Hi Team,
Could you please approve the above request, since we are still facing the issue. Thanks!

**Comment by priyas16** [comment]
Hi @eyarz,

Thank you so much for approving and merging the PR, the issue is resolved! Hence will close this request.

**Comment by priyas16** [comment]
Hi @eyarz,

Thank you so much for approving and merging the PR, the issue is resolved! Hence will close this request.
