### ISSUE TITLE
./crd-extractor.sh fails with two CRDs of the same short name. (externalsecrets)

### ISSUE THREAD

**Issue by cep21** [datreeio/CRDs-catalog#42]
My cluster has CRDs for two things both called short name `externalsecrets`

```
< kubectl get crd | grep externalsecret
externalsecrets.external-secrets.io                        2022-05-03T00:44:59Z
externalsecrets.kubernetes-client.io                       2020-12-30T18:45:17Z
```

With one type installed, `kubectl get externalsecrets` and it will get some.  However, since both are trying to be `externalsecrets` that command only fetches the first kind (not the second), and the full CRD name is required to pick the correct one.

Is it possible to have crd-extractor extract both kinds of external secrets.

Right now it only extracts the first kind.

**Comment by hadar-co** [comment]
@cep21 thanks:) the issue was fixed and a new release is now available
