### ISSUE TITLE
Problematic CRD imported from bitnami sealed secrets

### ISSUE THREAD

**Issue by gilbahat** [datreeio/CRDs-catalog#45]
Hi,

the bitnami sealed secrets CRD is problematic and will poison other schema validations. By design, this is an extensible CRD of the following form:
```

{
  "type": "object",
  "properties": {
    "spec": {
      "type": "object",
      "x-kubernetes-preserve-unknown-fields": true
    },
    "status": {
      "x-kubernetes-preserve-unknown-fields": true
    }
  }
}
```

importing this schema will cause all otherwise unknown schema validations to succeed regardless of their contents:

```
- against correct schema -
✗ kubeconform -summary -output json -strict -schema-location default -schema-location ../schemastuff/CRDs-catalog/keda.sh/scaledobject_v1alpha1.json -verbose apps clusters infrastructure | more
<snip>
    {
      "filename": "redacted/keda.yaml",
      "kind": "ScaledObject",
      "name": "redacted",
      "version": "keda.sh/v1alpha1",
      "status": "statusInvalid",
      "msg": "For field spec.triggers.0.metadata.value: Invalid type. Expected: string, given: integer"
    },

- against sealedsecrets schema -
✗ kubeconform -summary -output json -strict -schema-location default -schema-location ../schemastuff/CRDs-catalog/bitnami.com/sealedsecret_v1alpha1.json -verbose apps clusters infrastructure | less
    {
      "filename": "redacted/keda.yaml",
      "kind": "ScaledObject",
      "name": "redacted",
      "version": "keda.sh/v1alpha1",
      "status": "statusValid",
      "msg": ""
    },

```
I believe this schema should be somehow limited in scope or otherwise not imported to the CRD database until it can be contained properly

**Comment by eyarz** [comment]
I'm not sure I understand the issue here, so forgive me if I'm pointing you in the wrong direction 😅

From what I see, you're passing a schema to a specific manifest file.
Therefore, Kubeconform is performing a "stupid" compare, and because `sealedsecret_v1alpha1.json` schema has (almost) no restrictions, the check is passing.
If you use Kubeconform to perform a "smart" compare, based on the kind type (`ScaledObject`) it will not use the `sealedsecret_v1alpha1.json` schema to validate your manifest. 

In your case, to do the smart compare, you will need to run this command:
```
kubeconform -summary -output json -strict -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -verbose apps clusters infrastructure
```

`{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}` are not placeholders, they are Go params that Kubeconform inject to grab the right schema for each kind type.

**Comment by gilbahat** [comment]
Well, with the dearth of details in the schema, I don't see how an intelligent match would even be possible. And indeed running the 'smart' option does not pick up SealedSecret:

```
✗ kubeconform -summary -output json -strict -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -verbose apps clusters infrastructure | less

    {
      "filename": "redacted.yaml",
      "kind": "SealedSecret",
      "name": "redacted",
      "version": "bitnami.com/v1alpha1",
      "status": "statusError",
      "msg": "could not find schema for SealedSecret"
    },
```

That's how I got to this point to begin with: given that SealedSecret wasn't detected (and is not detectable) I tried a 'dumb' import and luckily noticed the result was one I did not expect. So as things are right now, this schema is nothing but rope to hang oneself with.

**Comment by hadar-co** [comment]
@gilbahat 
Looks like there is a typo in the catalog, the folder name is **bitamin.io** instead of **bitnami.com**.
Will fix that and let you know so you can try again:)

**Comment by hadar-co** [comment]
@gilbahat 
Done, please try running validation again

**Comment by eyarz** [comment]
it will work now :)
![image](https://user-images.githubusercontent.com/19731161/187070851-94aa545a-0213-4969-bccf-783ab8598948.png)
