### ISSUE TITLE
getting permission denied to push a feature branch with json schema

### ISSUE THREAD

**Issue by ee07dazn** [datreeio/CRDs-catalog#53]
![Screenshot 2022-09-01 at 17 47 34](https://user-images.githubusercontent.com/46483973/187968761-c84483b7-ba63-43b3-a7a0-7e2deb68a2af.png)

**Comment by eyarz** [comment]
this is a git error.
are you trying to push directly to datreeio/CRDs-catalog? I will not work because you need to open a PR.

**Comment by ee07dazn** [comment]
thanks, yes i was trying to push a feature branch here and then open a PR...but i see what needs to be done instead. Thx!
