### ISSUE TITLE
Add CRDs for AzureKeyVaultSecrets

### ISSUE THREAD

**Issue by Karsten-Fyhn** [datreeio/CRDs-catalog#59]
I would like to have the CRDs for the AzureKeyVaultSecret ressource from the https://akv2k8s.io/ project included in this repo. I have made a PR for this here: https://github.com/datreeio/CRDs-catalog/pull/58

**Comment by eyarz** [comment]
I'm also adding a link to the CRDs in this project for future reference:
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/tree/master/crds

**Comment by eyarz** [comment]
in prod 🥳

![image](https://user-images.githubusercontent.com/19731161/192780031-20e1352c-63dc-4eed-949d-292d7ef823ae.png)
