### ISSUE TITLE
add DopplerSecret CRD

### ISSUE THREAD

**Issue by ryan-blunden** [datreeio/CRDs-catalog#61]
https://github.com/DopplerHQ/kubernetes-operator

**Comment by eyarz** [comment]
CRD: https://github.com/DopplerHQ/kubernetes-operator/blob/main/config/crd/bases/secrets.doppler.com_dopplersecrets.yaml
kind: DopplerSecret
group: secrets.doppler.com
Example: https://github.com/JesusFilm/core/blob/6539dde1ac8ca4d3fd01fbf48109b5ab32502bfb/resources/kube/doppler-secret/doppler-secret.yaml
