### ISSUE TITLE
Automation 

### ISSUE THREAD

**Issue by diskmanti** [datreeio/CRDs-catalog#80]
Hello,

I stumbled upon this repo and it is a very cool idea.
I wanted to add some CRDs for openshift operators, since openshift is the k8s distribution we use at my company.

But I am not sure how the CRDs are generated. Is there some kind of automaton or is it copy pasted by hand.
Thank you,
Amanti

**Comment by eyarz** [comment]
@diskmanti if you only want to validate your OpenShift CRDs, the [CRD Extractor](https://github.com/datreeio/CRDs-catalog#crd-extractor) should work for you. It will extract the CRD from your cluster and convert them into local JSON schema files that you can pass to your schema validator tool.

If you want to validate OpenShift native objects, it's a [different process](https://github.com/datreeio/datree/issues/828).

**Comment by diskmanti** [comment]
Hello @eyarz 

Thank you for your feedback.

One last question please. index.yaml file is only used to create the github pages site or it has some other automation purpose?

thank you

**Comment by eyarz** [comment]
It will be used in the future for some planned automation.
If you want to use it, take in mind that it's not up to date right now.

**Comment by diskmanti** [comment]
I understand.

Thank you for the feedback
