### ISSUE TITLE
monitoring.coreos.com/servicemonitor_v1.json - missing support for the enableHttp2 field

### ISSUE THREAD

**Issue by martinrw** [datreeio/CRDs-catalog#95]
In https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml
There is a field called enableHttp2.
It seems like the servicemonitor schema (https://github.com/datreeio/CRDs-catalog/blob/main/monitoring.coreos.com/servicemonitor_v1.json) is unaware of this field and I get the following error with kubeconform:

` "For field spec.endpoints.0: Additional property enableHttp2 is not allowed"`

I think the schema may simply just need updating but my attempt at using the crd-extractor tool gives me the same output that we currently have and the enablehttp2 field isn't mentioned anywhere

**Comment by hadar-co** [comment]
Hi @martinrw , it is worth checking to see if there is a new version of the schema, but in the meantime you can use the `--permissive-schema` flag to allow additional properties.

**Comment by martinrw** [comment]
Hey @hadar-co 
Thanks for the quick reply and your suggestion. 
I am using the latest schemas from this repo.

We are using the kubeconform command and not datree so that's not an option unfortuantely.
This is my first time really looking at this but I think the workaround for now might be to change:
`"additionalProperties": false`
to 
`"additionalProperties": true`
in my local copy of monitoring.coreos.com/servicemonitor_v1.json for now.
or maybe even delete this line altogether.
It's Friday afternoon now so I'll have a play with it next week

**Comment by hadar-co** [comment]
Well, kubeconform allows additional properties by default, are you setting the `-strict` flag by mistake?

If you want to send the schema I can take a closer look:)

**Comment by martinrw** [comment]
Thanks for the offer to look. We aren't using the strict flag but I think this setting within the schemas:
`"additionalProperties": false`
is effectively doing the same thing as strict.
I have adjusted my copy of the schemas to have:
`"additionalProperties": true`
everywhere and now it seems OK.

The ideal solution would be for the schemas to be updated but at least so I think this ticket is still valid, but at least I can continue for now

**Comment by eyarz** [comment]
@martinrw I think I found the root cause for this issue.
The last update to the schema in this repo for `servicemonitor_v1` was on Jun 2022.
`enableHttp2` was added to the original schema (on the helm-charts repo) [20 days ago](https://github.com/prometheus-community/helm-charts/blame/main/charts/prometheus-operator-crds/templates/crd-servicemonitors.yaml#L158):
![image](https://user-images.githubusercontent.com/19731161/211491155-9146d902-3d9e-4028-b2cd-8a13037170d7.png)
therefore, updating the schema in [this repo](https://github.com/datreeio/CRDs-catalog/blob/main/monitoring.coreos.com/servicemonitor_v1.json) will solve your issue :)

**Comment by martinrw** [comment]
Hi @eyarz 
Thanks for looking at it. I identified the same thing, the schema is out of date.
I already have the up-to-date custom resource deployed in my cluster and I tried using the crd-extractor tool to generate a new schema from it but the result I got didn't include anything extra for the new http2 option.
If I get a chance a bit later I will try again in case I was doing something wrong
