### ISSUE TITLE
kustomize resource (non-custom) definitions

### ISSUE THREAD

**Issue by wyardley** [datreeio/CRDs-catalog#99]
I am guessing this project isn't the right place to host `kustomize.config.k8s.io` resource definitions, since they're builtin, and not custom. However,  they're also not hosted on the project we typically use that has the main schemas (see context in https://github.com/yannh/kubernetes-json-schema/issues/13).

Is it reasonable to assume that since they're not "custom", they shouldn't be added here?

**Comment by wyardley** [comment]
note: these are different from the flux kustomize types which are already included here
https://fluxcd.io/flux/faq/#are-there-two-kustomization-types

**Comment by eyarz** [comment]
The main reason why NOT to host the schema in this project (or `yannh/kubernetes-json-schema`) is that it will just not work 😅

Kubconform relies on the `kind` property to match the manifest with the right schema. 
Kustomize manifests can be valid also without this property, they are "just" yaml files...

You have this open-source project that is hosting the kustomize schema:
https://json.schemastore.org/kustomization.json

**Comment by wyardley** [comment]
Thanks! Yes, I tried using the schema above earlier, and it seemed to work (I believe ours do have the `kind` property defined), but it wasn’t clear which version(s) it referred to.

Thanks for merging my PRs, btw!

**Comment by gecube** [comment]
> Kustomize manifests can be valid also without this property, they are "just" yaml files...

anyway most of kustomize manifests mimic k8s manifests and include apiversion and kind - like kubeadm config files also do. So it would be nice to have a proper schema file which I could not find.

**Comment by wyardley** [comment]
IIRC, the one above did work in my testing, though it’s been a while.
